### ISSUE TITLE
Method implementations in .h files

### ISSUE THREAD

**Issue by raistlinmolina** [jrowberg/i2cdevlib#390] opened 2018-07-29 17:26 UTC
Hi Jeff, 

First of all thanks for the great library.

I found this problem when encapsulating the MPU6050_6Axis_MotionApps20.h file into a convenience class of mine.

I came across a "previously defined here" error when linking.

The issue is that in that .h file there are some method implementations that cause the build process to compile them twice and then include when linking.

I created a .cpp file and moves those methods there while maintaining the rest in the .h file, now all compiles and links.

Would it be better to do the same in your library?.

Thanks in advance.

**Comment by jrowberg** [comment] 2021-09-26 03:09
Closing this as a duplicate of many others, concerning a problem that will be fixed in the next week or so.

**Closed by jrowberg** 2021-09-26 03:09 UTC
